functionality:
  name: generate_report
  arguments:
    - name: "--input"
      type: file
      direction: input
    - name: "--output"
      type: file
      direction: output
  resources:
    - type: python_script
      path: script.py
  platforms:
    - type: docker
      image: python:3.9
      setup:
        - type: python
          packages:
            - pandas
            - matplotlib
            - fpdf
    - type: nextflow
    - type: native