functionality:
  name: filter_timesheets
  arguments:
    - name: "--input"
      type: file
      direction: input
    - name: "--year"
      type: integer
      direction: input
    - name: "--min_duration_per_project"
      type: integer
      direction: input
    - name: "--output"
      type: file
      direction: output
  resources:
    - type: python_script
      path: script.py
  platforms:
    - type: docker
      image: python:3.9
      setup:
        - type: python
          packages: pandas
    - type: nextflow
    - type: native